// Dart Autogenerated Xamarin Class
import 'package:flutnet_notes_bridge/flutnet_notes/service_library/note.dart';

extension NoteExtension on Note {
  Note copyWith({
    int iD,
    String title,
    String content,
    bool isImportant,
    DateTime date,
  }) {
    return Note(
      iD: iD ?? this.iD,
      title: title ?? this.title,
      content: content ?? this.content,
      isImportant: isImportant ?? this.isImportant,
      date: date ?? this.date,
    );
  }
}
